# Build stage
FROM golang:1.24.4-alpine AS builder

WORKDIR /app

COPY . .
RUN go mod download && go build -o app ./cmd/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/app .

EXPOSE 8081

CMD ["./app"]
